# Generated by Django 5.2.7 on 2025-11-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resume",
            name="unique_user_resume_title",
        ),
    ]
